name: Build and Test with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.x  # Use the latest stable version of Go

      - name: Build
        run: go build ./...  # Build all Go packages

  test-and-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.x  # Use the latest stable version of Go

      - name: Test with Coverage
        run: |
          mkdir -p TestResults/CoverageReport
          go test ./... -coverprofile=coverage.out
          go tool cover -html=coverage.out -o TestResults/CoverageReport/coverage.html
          go tool cover -func=coverage.out

      - name: Install ReportGenerator
        run: |
          go install github.com/wadey/gocovmerge@latest
          go install github.com/matm/gocov-html@latest

      - name: Generate coverage report (Lcov)
        run: gocov-html -o TestResults/CoverageReport/lcov.info coverage.out

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./TestResults/CoverageReport/lcov.info

      - name: Deploy Coverage Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PTA }}
          publish_dir: ./TestResults/CoverageReport
          publish_branch: gh-pages
          commit_message: "Update code coverage report"
