name: Build and Test with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.x  # Use the latest stable version of Go

      - name: Build
        run: go build ./...  # Build all Go packages

  test-and-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.x  # Use the latest stable version of Go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v

      - name: Run coverage
        run: go test ./... -v -coverprofile=covprofile

      - name: Build HTML coverage
        run: |
          mkdir -p TestResults/CoverageReport
          go tool cover -html=covprofile -o TestResults/CoverageReport/coverage.html

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TestResults/CoverageReport
          publish_branch: gh-pages
          commit_message: "Update code coverage report"
